### GET all users
GET http://localhost:3001/api/users/all

### GET Dieter!
GET http://localhost:3001/api/users/?name=dieter


### GET Flexie Condition!
GET http://localhost:3001/api/users/?name=ie



### GET Dieter!
GET http://localhost:3001/api/users/?username=o




### DELETE a user
DELETE http://localhost:3001/api/users/?name=dieter


### POST Create a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Vonnegurt",
  "username": "Schlachter Nr. 5",
  "age": 10,
  "mail": "anonymous@www.de",
  "password": "1234"
}

### POST Create a user fails
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Vonnegurt",
  "username": "Schlachter Nr. 5",
  "age": 0
}

### User Login
Post http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "RealJuliusCaesar",
  "password": "1234"
}

### GET current user
GET http://localhost:3001/api/me


### POST logout
Post http://localhost:3001/api/logout

