### GET all users
GET http://localhost:3001/api/users/all

### GET Dieter!
GET http://localhost:3001/api/users/?name=Dieter
### GET Dieter!
GET http://localhost:3001/api/users/?username=Dietonator
### GET Dieter!
GET http://localhost:3001/api/users/?age=34



### DELETE a user
DELETE http://localhost:3001/api/users/?username=Dietonator


### POST Create a user
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Dieter",
  "username": "Dietonator",
  "age": 34,
  "mail": "awesomedieter1337@www.de",
  "password": "1234"
}

### POST Create a user fails
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Vonnegurt",
  "username": "Schlachter Nr. 5",
  "age": 0
}

### User Login
Post http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "Dietonator",
  "password": "1234"
}

### GET current user
GET http://localhost:3001/api/me


### POST logout
GET http://localhost:3001/api/logout

